### ISSUE TITLE
Is the consesus virtual?

### ISSUE THREAD

**Issue by zkSystems** [maidsafe/parsec#62]
Trying to understand the algorithm, the following is not completely clear to me:

Do nodes communicate their estimate, bin_value, aux and decision via gossip to other peers, or do they compute these values just internally? I think they don't because packedEvent does not contain any of this. Or am I on the wrong path?

**Comment by pierrechevalier83** [comment]
I'm guessing you're the same person who asked this question on the forum. I answered over there: 
https://safenetforum.org/t/is-the-binary-consensus-part-in-parsec-virtuel/24970/3

To re-iterate the point for by-passers:

> Indeed, they’re all virtual in PARSEC. The mechanism is the same as in the original paper (minus common coin) but we’re doing this based on meta-votes (Do we think a given node’s observation should be considered when deciding the next stable events?). We do send the information needed to generate these virtual observations by gossiping all transactions to each other. (Gossip guarantees that each node will be able to construct the exact same DAG. You can prove the DAG you have is the same everyone else has received or will eventually receive up to the latest event you strongly see [that takes care of forks])
