### ISSUE TITLE
Tests or example usage?

### ISSUE THREAD

**Issue by markwylde** [maidsafe/parsec#9]
Do you guys have any sample code or tests you could share to show how to use the library? Or is it very tied into the MaidSafe software stack?

**Comment by ustulation** [comment]
This is the first iteration, so we are still in the midst of coding it just now. You can follow the progress in JIRA for the goals of [Milestone-1](https://maidsafe.atlassian.net/browse/MAID-2756) and browse for sub-tasks for the _epic_.
